#cloud-config

hostname: etcd
coreos:
  fleet:
    etcd_servers: http://127.0.0.1:4001
    public-ip: $private_ipv4 
    metadata: role=etcd
  etcd:
    name: etcd
    addr: $private_ipv4:4001
    bind-addr: 0.0.0.0
    peer-addr: $private_ipv4:7001
    cluster-active-size: 1
    snapshot: true
  units:
    - name: etcd.service
      command: start
    - name: fleet.service
      command: start
    - name: docker.service
      mask: true
  update:
    group: alpha
    reboot-strategy: off
